# Generated by Django 4.2 on 2024-09-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_phone_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
