# Generated by Django 4.2 on 2024-09-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_phone_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='model',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='PhoneModel',
        ),
    ]
