# Generated by Django 4.2 on 2024-09-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_brand_country_alter_phone_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'کشور', 'verbose_name_plural': 'کشورها'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'تلفن', 'verbose_name_plural': 'تلفن\u200cها'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='warehouse.country', verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام رنگ'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کشور'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_set', to='warehouse.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_set', to='warehouse.country', verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='display_size',
            field=models.FloatField(verbose_name='اندازه نمایشگر'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='model',
            field=models.CharField(max_length=50, unique=True, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('available', 'موجود'), ('unavailable', 'نا موجود')], max_length=100, verbose_name='وضعیت'),
        ),
    ]
