# Generated by Django 4.2 on 2024-09-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_brand_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام کشور'),
        ),
    ]
