# Generated by Django 4.2 on 2024-09-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_phone_search_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='search_query',
        ),
    ]
